# Start with the latest rbatch
FROM openapx/rbatch:latest-debian


# -- dockerfile scaffolding
#    (1) add license file to root directory
#    (2) directory scaffolding

COPY LICENSE /LICENSE-rworkbench
RUN  chmod u+r-wx,g+r-wx,o+r-wx /LICENSE-rworkbench && \
     mkdir -p /opt/openapx/config/rworkbench


# -- configuration files
#    note: this is the input location for Shell scripts below
#    note: wildcard trick on libs-* is to copy if it exists

COPY libs-debia* /opt/openapx/config/rworkbench/

RUN find /opt/openapx/config/rworkbench -type f -exec chmod u+r-wx,g+r-wx,o-rwx {} \; && \
    find /opt/openapx/config/rworkbench -type d -exec chmod u+rx-w,g+rx-w,o-rwx {} \;



# -- scripted sequence
#    1) add binary library dependencies
#    2) install workbench
#    3) clean up

COPY --chmod=755 scripts/rworkbench/install_workbench.sh /scripts/rworkbench/
RUN /opt/openapx/utilities/bin-libs.sh /opt/openapx/config/rworkbench/libs-debian && \
    /scripts/rworkbench/install_workbench.sh https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2024.04.2-764-amd64.deb && \
    rm -Rf /scripts /sources


# -- configure container to run Workbench
EXPOSE 8787

COPY --chmod=755 scripts/rworkbench/entrypoint.sh /entrypoint.sh
ENTRYPOINT /entrypoint.sh


# -- add any additional utilities
COPY --chmod=755 scripts/rworkbench/rworkbench_adduser.sh /opt/openapx/utilities/

RUN find /opt/openapx/utilities -type f -exec chmod u+rx-w,g+rx-w,o-rwx {} \; && \
    find /opt/openapx/utilities -type d -exec chmod u+rx-w,g+rx-w,o-rwx {} \;






